baseURL = "https://blog.pys.im/"
languageCode = "zh-cn"
enableEmoji = true
enableGitInfo = true

[Params]
googleAnalyticsId = "G-XV3J4FRK59"
favicon = "ðŸŒŒ"
cover = "https://cdn.jsdelivr.net/gh/pys1992/storage@main/20210207133529.jpg"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
[markup.highlight]
style = "monokai"

[markup.goldmark.renderer]
unsafe = true

[frontmatter]
lastmod = [":default"]